#!/bin/sh
# Place this in /media/data/local/sbin
#Local conf path
LCONF_PATH=/media/data/local/home/.deepsleep
NO_RA_FLAG=$LCONF_PATH/dontbootretroarch.flag
LAST_GAME=$LCONF_PATH/last_game.txt
RA=/media/data/local/bin/retroarch_rg350

if [ -e $NO_RA_FLAG ]; then
	/usr/bin/gmenu2x
else
	# Revert back to gmenu2X by holding start button at boot
	if dialog --stdout --timeout 2 --title "Load gmenu2X?" \
        	  --backtitle "Boot Options" \
         	 --yesno "Yes: Load gmenu2X, No: Load Retroarch\nAfter 2 seconds Retroarch will load automatically." 7 60; 
	then
	    mkdir -p $LCONF_PATH
	    echo "dontbootretroarch" > $NO_RA_FLAG
	    /usr/bin/gmenu2x
	else
	    touch $LAST_GAME
	    # Dirty script to locate the game rom and its core (The opendingux grep does not allow perl expressions)
	    awk -F": " 'NR==11{print $2, $3}' /usr/local/home/.retroarch/content_history.lpl > $LAST_GAME
	    awk -F": " 'NR==13{print $2, $3}' /usr/local/home/.retroarch/content_history.lpl >> $LAST_GAME
	    
	    PATH_GAME=$(awk -F"\"" 'NR==1{print $2}' $LAST_GAME)
	    CORE_PATH=$(awk -F"\"" 'NR==2{print $2}' $LAST_GAME)
	  
	    touch $LAST_GAME.old
	    rm $LAST_GAME.old
	    mv $LAST_GAME $LAST_GAME.old
	    
 
	    $RA -L "$CORE_PATH" "$PATH_GAME"
	    sleep 1
	    # when retroarch quits -> we turn it off
	    /sbin/poweroff
	fi
fi
